### ISSUE TITLE
Result.map doesn't handle exceptions, as described in the readme

### ISSUE THREAD

**Issue by sfesenko** [spencerwi/Either.java#3]
Next scenario from the readme fails, however it's expected that it'll wrap exceptions from chained methods

```java
@Test
public void map() {
    Result<?> result = Result.attempt(() -> someOperationThatMightFailOrReturnA())
            .map(a -> someOtherOperationThatMightFailOReturnB(a))
            .map(b -> someThirdOperationThatMightFailOrReturnC(b));
    Assert.assertTrue(result.isErr());
}

private Object someThirdOperationThatMightFailOrReturnC(Object b) {
    return Objects.requireNonNull(b);
}

private Object someOtherOperationThatMightFailOReturnB(Object a) {
    return Objects.requireNonNull(a);
}

private Object someOperationThatMightFailOrReturnA() {
    return null;
}
```
```
java.lang.NullPointerException
	at java.util.Objects.requireNonNull(Objects.java:203)
	at com.spencerwi.either.ResultMapTest.someOtherOperationThatMightFailOReturnB(ResultMapTest.java:27)
	at com.spencerwi.either.ResultMapTest.lambda$map$1(ResultMapTest.java:16)
	at com.spencerwi.either.Result$Ok.map(Result.java:108)
```

**Comment by spencerwi** [comment]
Fixes, thanks to your PR!
